dist: trusty
addons:
  apt:
    packages:
      - texlive-base
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - latexmk
      - lmodern
      - pgf

script:
  - cd tex
  - make
